Submitted batch job 7906026
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
Loading the csv file...
Traceback (most recent call last):
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/common_files/mono_detec_mix.py", line 26, in <module>
    data_raw = fu.loadCsvOutput(imputFileName)
  File "/m100_work/FUSIO_ja6HeBub/nmatsuda/python_modules/FFT_utility.py", line 95, in loadCsvOutput
    ndarrayData = np.loadtxt(csvData, delimiter=",")
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/cineca/prod/opt/compilers/python/3.8.2/none/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: outp_1.csv not found.
